### docker-compose for nextcloud

services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud
    restart: unless-stopped
    environment:
      - MYSQL_HOST=nextcloud_db
      - MYSQL_PASSWORD=nc4321
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    ports:
      - "9321:80"
    volumes:
      - ./volumes/nextcloud/html:/var/www/html
    depends_on:
      - nextcloud_db
    networks:
      - default
      - nextcloud
  nextcloud_db:
    container_name: nextcloud_db
    image: mariadb
    restart: unless-stopped
    environment:
      - TZ=ASIA/SEOUL
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=nc4321
      - MYSQL_PASSWORD=nc4321
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - ./volumes/nextcloud/db:/config
      - ./volumes/nextcloud/db_backup:/backup
    networks:
      - nextcloud

networks:
  nextcloud:
