version: "3.8"
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./data:/var/lib/grafana
    user: root
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
      - GF_RENDERING_SERVER_URL=http://grafana_image_renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
    networks:
      - grafana_network

  grafana_image_renderer:
    build: ./grafana_image_renderer
    container_name: grafana_image_renderer
    restart: always
    ports:
      - 8081
    networks:
      - grafana_network

networks:
  grafana_network:
    driver: bridge
